### ISSUE TITLE
It is recommended to add compositors like `picom` or `compton` to achieve features such as transparency

### ISSUE THREAD

**Issue by eonun** [endeavouros-team/endeavouros-i3wm-setup#110]
Since I need the terminal in i3wm to have a transparent background, I made some configurations.

- Install the compositor `picom`
```sh
sudo pacman -S picom
```

- Configure i3wm to start `picom`
```ini
# Start picom in the i3wm configuration file
exec_always --no-startup-id picom -b
```

**Comment by killajoe** [comment]
What is the exact issue here?

https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/main/force-knowledge.md#no-transparency

https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/5af46523cec77185fde3b44b051eecd1d70e232b/etc/skel/.config/i3/config#L355
