### ISSUE TITLE
Disk, memory and cpu labels overlap values

### ISSUE THREAD

**Issue by pynmash** [endeavouros-team/endeavouros-i3wm-setup#112]
Experiencing an issue where the labels (fontawesome glyphs) are overlapping with the values they represent.

Temporarily I've resolved the issue by adding spaces (3 to be accurate) at the end of each label in i3blocks.conf, and that seems to work but I don't know if it's the best solution for everyone, or if there's a more universal option, and so haven't submitted a PR. I can do so if you'd like

**Comment by killajoe** [comment]
you have any extra glyph font package installed in addition?

**Comment by killajoe** [comment]
i see must be some change.. look:

![2024-05-10_23-18](https://github.com/endeavouros-team/endeavouros-i3wm-setup/assets/16797647/37210aae-81fc-41e1-bd49-e68c730a97c4)

![2024-05-10_23-20](https://github.com/endeavouros-team/endeavouros-i3wm-setup/assets/16797647/ce2528c5-9e14-4ca0-ae0d-84c248c90f65)

I would be happy if you would do a Pull Request for it.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/pull/113
done that with this commit thanks for the hint!
