### ISSUE TITLE
Play-Pause doesn't work

### ISSUE THREAD

**Issue by CoutHi** [endeavouros-team/endeavouros-i3wm-setup#117]
For me, the play pause function with playerctl wasn't working. I fixed it by changing 
bindsym XF86AudioPlay exec --no-startup-id playerctl play 
to 
bindsym XF86AudioPlay exec --no-startup-id playerctl play-pause
And commenting out the same function for pause.

**Comment by killajoe** [comment]
you want to do a Pull Request for the change?

**Comment by CoutHi** [comment]
> you want to do a Pull Request for the change?

I really wanted to but have no idea how

**Comment by CoutHi** [comment]
I just did the request, sorry if there are mistakes with it. Not quite versed in the etiquette yet.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/commit/4d7ed615c78c6af495c15f5eb3c9267f89a0e22c

**Comment by killajoe** [comment]
Thanks for your contribution, everyone needs to start somewhere me was the same some times ago.

**Comment by CoutHi** [comment]
Glad to have helped. It's a great i3 setup.

**Comment by killajoe** [comment]
> Glad to have helped. It's a great i3 setup.

and contributions like yours makes it stay like that !
