### ISSUE TITLE
Lock screen automation

### ISSUE THREAD

**Issue by pprevos** [endeavouros-team/endeavouros-i3wm-setup#136]
This config should have a default lock screen when the machine awakes or after a set time.

I got in trouble with IT security at my workplace for using a system without automatic locking.

How can I enable this feature?

**Comment by killajoe** [comment]
sry was busy doing other things.. i will have a look asap.

**Comment by killajoe** [comment]
would need something like: xss-lock and adding a config:
` sudo pacman -Syu xss-lock` 
and add this to your i3 config (~/.config/i3/config)
`exec_always --no-startup-id xset dpms 0 0 300`
`exec --no-startup-id xss-lock --transfer-sleep-lock -- "~/.config/i3/scripts/blur-lock"`

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/pull/141
