### ISSUE TITLE
consider other battery script

### ISSUE THREAD

**Issue by k2s** [endeavouros-team/endeavouros-i3wm-setup#26]
there is https://raw.githubusercontent.com/cytopia/i3blocks-modules/master/modules/battery

**Comment by killajoe** [comment]
the one used is this: https://github.com/vivien/i3blocks-contrib/blob/master/battery/battery
And without any detail about what the one you offered will make it better, i see no reason to randomly apply a new script ;)

**Comment by killajoe** [comment]
just added alternative script and change to battery scrips from i3-contrib
