### ISSUE TITLE
Picom exec in i3 config

### ISSUE THREAD

**Issue by al6263** [endeavouros-team/endeavouros-i3wm-setup#33]
HI, I want to open this issue to give attention to the picom exec command that you can find on the i3 config file 
I know that it is disabled by default but the command 
`exec --no-startup-id picom -b`
doesn't work when I apply the changes ( actually does with a reboot ) 
but if I do: 
`exec_always --no-startup-id picom -b`
will work perfectly after only a reload of i3wm I think this change could make the default experience better 

Cheers,
Al6263 ( EOS user )

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/commit/448c8ce092fc469d8769549594db52c8f23a5361

Thanks for the contribution!
