### ISSUE TITLE
Assorted blur-lock things

### ISSUE THREAD

**Issue by ghbrown** [endeavouros-team/endeavouros-i3wm-setup#42]
I was recently doing some digging to configure myself a combination lock and suspend on top of the base EndevourOS i3 and I had some thoughts for discussion.

- It appears the blur-lock implementation is a verbatim copy of [this repo](https://github.com/leonmutschke/i3lock-config), and it does not appear that any credit is given to the author(s). While their script is extremely useful, it is not complicated, but nevertheless it seems right to credit them given that it's a direct copy. Also, their code has no license, which could be a problem.
- There is an [umerged PR](https://github.com/leonmutschke/i3lock-config/pull/2) on said code that offers a very nice suggestion (adding `-z` to the `scrot` call to ensure no beep). On my system the beep is horrible and jolting, and I think this flag should definitely be added to our version.
- How do people feel about a lock+suspend entry in the menu, or replacing the command for the "suspend" with lock+suspend commands (my preference and current config)? Personally, I think this is much more useful and desirable than a plain suspend, and I believe most desktop environments also lean this way (calling it suspend and doing a lock+suspend). It also keeps from having a lock but no sleep/dark case, which I have had multiple times, and is quite frustrating and possibly bad for your screen.

**Comment by killajoe** [comment]
feel free to PR to this repo if you have anything to improve it !
Any help and addition is welcome.
