### ISSUE TITLE
Monitor brightness

### ISSUE THREAD

**Issue by hophiphip** [endeavouros-team/endeavouros-i3wm-setup#57]
## Description
Hi. Monitor brightness control keys (`XF86MonBrightnessUp` & `XF86MonBrightnessDown`) might not work out of the box on some systems.

## Issue
In i3 config `xbacklight` is used to control brightness. 
But `xbacklight` only works with Intel drivers (see: https://wiki.archlinux.org/title/backlight).

## Steps to reproduce
* CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics

Command:
```sh
xbacklight -get
```
will return `No outputs have backlight property`.

## Possible fix
1. Install [acpilight](https://gitlab.com/wavexx/acpilight) that is backward-compatibile with `xbacklight` - so there would be no need to change i3 config. 
2. Add current user to the `video` group (as mentioned in: https://gitlab.com/wavexx/acpilight/-/issues/16) to allow user to update brightness.

**Comment by killajoe** [comment]
video group is a so called Pre-systemd groups  and should not be needed on arch using systemd.
The issue is also 4 years old .. but seems smart to change to [acpilight](https://gitlab.com/wavexx/acpilight) not sure why it would need a change in i3 config if it is fully backward compatible?

**Comment by hophiphip** [comment]
> .. not sure why it would need a change in i3 config if it is fully backward compatible?

oops, its a typo. Migrating from `xbacklight`  to [acpilight](https://gitlab.com/wavexx/acpilight) doesn't require config change.

**Comment by hophiphip** [comment]
closing the issue as it seems not related to `endeavouros-i3wm-setup`
