### ISSUE TITLE
icons shrunk

### ISSUE THREAD

**Issue by ecabigting** [endeavouros-team/endeavouros-i3wm-setup#58]
![2022-09-12-10:05:44-screenshot](https://user-images.githubusercontent.com/14327951/189584590-61ec329f-b33c-469a-b405-e39bab2135b9.png)

This happen after I update 09/12/2022. 

I am on i3wm, endeavourOS.

I also check the config for i3, nothing looked change/different.

**Comment by killajoe** [comment]
> I also check the config for i3, nothing looked change/different.
i3 configs will never change on updates we do not do that.. 
I have several installed i3 systems here none have this issue after update.. but i know from before that this could happen if you have installed other iconic font packages.. 
Like nerdfonts or other package that ships awesome fonts. 
check this please: 
```
pacman -Qs nerd
pacman -Qs awesome
```

**Comment by ecabigting** [comment]
Hey! Thanks for the reply!

Here is what I have:

![fonts](https://user-images.githubusercontent.com/14327951/191016046-f0be52be-1c2c-4c5d-aaa2-7772eb86da7a.png)

**Comment by killajoe** [comment]
You will need to do the one or the other ;)
You can uninstall ttf-iosevka-nerd  or you need to check the iconic icon fonts in the configs to change them in size. 
The config original using awesome-terminal-fonts so if you add others they will change..
