### ISSUE TITLE
Font for title bars in this repo

### ISSUE THREAD

**Issue by mtkleet** [endeavouros-team/endeavouros-i3wm-setup#62]
Could you upload or provide source for default font used for this config, please? It was patched Noto Sans I think. Mine was overwritten by another one.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/47e0d033ec302178d146110c354c5140c1508040/.config/gtk-3.0/settings.ini#L2

https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/47e0d033ec302178d146110c354c5140c1508040/.config/i3/config#L491

https://github.com/endeavouros-team/EndeavourOS-packages-lists/blob/master/i3
