### ISSUE TITLE
Keyboard map

### ISSUE THREAD

**Issue by reinaldorauch** [endeavouros-team/endeavouros-i3wm-setup#63]
Where the instalation gets the default keyboard configuration?

edit: all i can found online are paliative solutions regarding calls of setxkbdmap in i3 config but I want to change the original configuration

**Comment by killajoe** [comment]
This is done systemwide not per user or DE/WM setup.. 
You set this up on install process inside calamares.. 
https://i0.wp.com/endeavouros.com/wp-content/uploads/2022/06/3-1.png?resize=768%2C465&ssl=1

**Comment by killajoe** [comment]
For any extra info the forum would be the place: 
https://forum.endeavouros.com/

**Comment by reinaldorauch** [comment]
Yeah, sure but after the instalation there isnt a place to change that, or a obvious one at least

**Comment by killajoe** [comment]
Using a WM.. and setting keymap.. are two different things as i said i´this is set systemwide while installing the system and the info to change this is the same as archwiki say about it. there is no gui to do that you need to edit config manually.. 
`localectl status`   show what you have..
` localectl set-keymap --no-convert keymap`   where _keymap_ is one you can get from this list:
` localectl list-keymaps | grep -i search_term`  _search_term_  is something you search for like _en_ for english

**Comment by reinaldorauch** [comment]
Ah, yes, so in i3 the right place to change is in .config/i3/config then?

**Comment by killajoe** [comment]
setxkbmap  command can do that.. if you need to have it changed in a case to case scenario.. if you want to change default to bwe different set iot systemwide is the better option.. ( using localectl )   
The switcher in i3 config is for the case to switch between two setups on the run.

**Comment by killajoe** [comment]
But as i mentioned already.. this is usually not the place for teaching lessons..  or tutorials.. GitHub is used for developing and resolving issues on the code and configs. (sources) 
The right place for help is the forum or the telegram chat and also reddit ..
