### ISSUE TITLE
Typo: 'then' instead of 'than'

### ISSUE THREAD

**Issue by Hazzatur** [endeavouros-team/endeavouros-i3wm-setup#66]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/9d5ce21eea7b44434d99ac68594df03b61bc9c80/.config/i3/config#L317

Additional proposed change: 
```
# automatic focus of new window if it is opened in a workspace other than the current:
```

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-i3wm-setup/commit/32c4e9d3a8e8a7ce71a0483a4e00e2e6bd74ae4e
thanks ;)
