### ISSUE TITLE
missing nice wallpaper

### ISSUE THREAD

**Issue by triklsbg** [endeavouros-team/endeavouros-i3wm-setup#67]
Reason: feh is called in config but not installed as package

**Comment by killajoe** [comment]
it is.. you will need the latest ISO:
https://github.com/endeavouros-team/calamares/blob/c58f27cf4d3b40160015a18e1dceee31a3bffe3b/data/eos/modules/netinstall.yaml#L281

https://endeavouros.com/latest-release/
