### ISSUE TITLE
help with icons

### ISSUE THREAD

**Issue by Toni500github** [endeavouros-team/endeavouros-i3wm-setup#88]
Hi! 
I've been using Linuxmint 20.3 since 2021 and I've decided to switch to EndeavourOS some weeks ago. 
When I have installed EndeavourOS, I've choosen to install the official i3 flavour and after install, I booted to i3 and the icons in the menus were normal. After I have extracted my old `~`, which it had a LOT OF fonts in `~/.fonts` and `~/.local/share/fonts`, they were not as they were before

e.g the powermenu 
![scrot](https://github.com/endeavouros-team/endeavouros-i3wm-setup/assets/88878648/46231cb0-4db2-4421-b14f-f4b4a85ba870)

the battery mode menu
![scrot2](https://github.com/endeavouros-team/endeavouros-i3wm-setup/assets/88878648/d09a0416-978c-4ad7-a672-391154fd7bb2)

`fc-list`
[fc-list.txt](https://github.com/endeavouros-team/endeavouros-i3wm-setup/files/13215775/fc-list.txt)

`fc-list | awk -F ":" '{ print $2 }' | uniq`
[fc-list2.txt](https://github.com/endeavouros-team/endeavouros-i3wm-setup/files/13215793/fc-list2.txt)

this is probably my fault with all these fonts i have on my ~ 😅

**Comment by killajoe** [comment]
the EndeavourOS setup is using [awesome-terminal-fonts](https://archlinux.org/packages/extra/any/awesome-terminal-fonts/) package  if you install other iconic font providers you need to recheck the used icons.. some packages providing the same others are different in spacing e.t.c.  all the stuff is configured with simple configs and scripts.. these two you screenshotted are these:  

* https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/ca8cbab1838f70456d94e1a90beea0c8add7ec26/etc/skel/.config/i3/scripts/powermenu#L116
 
* https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/ca8cbab1838f70456d94e1a90beea0c8add7ec26/etc/skel/.config/i3/scripts/power-profiles#L123

you ma simply add a space to the lines where the icons are spaced wrongly:
 [  Shutdown]="systemctl poweroff"  (before shutdown in example) 

And the best place to ask general questions about configuration changes is not the source repository.. it is the forum or the telegram chat.
