### ISSUE TITLE
archlinux

### ISSUE THREAD

**Issue by adrian-agp** [endeavouros-team/endeavouros-i3wm-setup#91]
Hello how can I install endeavouros-i3wm-setup in my arch base

**Comment by killajoe** [comment]
you will need to edit packages list..

**Comment by killajoe** [comment]
remove these:
endeavouros-skel-i3wm
endeavouros-xfce4-terminal-colors
eos-lightdm-slick-theme

exchange these 
eos-qogir-icons  -->   qogir-icon-theme (AUR)
arc-gtk-theme-eos  -->  arc-gtk-theme (arch-repo)

**Comment by adrian-agp** [comment]
@killajoe 
thanks for the reply, add repos from endeavouros, install without modifying the files, but I have a problem I'm not using Display Manager: it's necessary one??, edit vim ~/.xinitrc add exec i3 at the end, but when restarting the session I have to run startx, some help with this...

**Comment by killajoe** [comment]
not really the place to ask such questions here as this is about development and maintainment of the configs basically.. you sould read here:
https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login
I will close here .. feel free to go to our Forum or Telegram we do not mind if archusers asking for help there.

https://forum.endeavouros.com
https://t.me/Endeavouros

**Comment by killajoe** [comment]
closing
